# Generated by Django 2.2.7 on 2020-01-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='s_or_p',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
