# Generated by Django 2.2.7 on 2020-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_website_app', '0002_guest_s_or_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='s_or_p',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='special_diet',
        ),
        migrations.AddField(
            model_name='guest',
            name='diet_message',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='diet_restriction',
            field=models.CharField(choices=[('none', 'none'), ('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('other', 'other')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_peggy_friend_relative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_shu_friend_relative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='number_of_guests',
            field=models.IntegerField(),
        ),
    ]
